--1ª Quantas corridas por dia tivemos nesse período?
SELECT 
    COUNT(*) AS TOTAL_CORRIDAS,
    DATE(STARTED_AT) AS DIA
FROM AT_SINCRONA_BD_POS_UNIFAP_01
GROUP BY DATE(STARTED_AT)
ORDER BY DATE(STARTED_AT) 

--1ª Qual a média de corridas por dia?
WITH CORRIDAS_DIA AS  (
	SELECT 
	    COUNT(*) AS TOTAL_CORRIDAS_DIA,
	    DATE(STARTED_AT) AS DIA
	FROM AT_SINCRONA_BD_POS_UNIFAP_01
	GROUP BY DATE(STARTED_AT) 
)
SELECT AVG(TOTAL_CORRIDAS_DIA) FROM CORRIDAS_DIA;

--1ª Qual a média de corridas por mês?
WITH CORRIDAS_MES AS  (
	SELECT 
	    COUNT(*) AS TOTAL_CORRIDAS_MES,
	    STRFTIME('%Y-%m',STARTED_AT) AS MES
	FROM AT_SINCRONA_BD_POS_UNIFAP_01
	GROUP BY STRFTIME('%Y-%m',STARTED_AT) 
)
SELECT AVG(TOTAL_CORRIDAS_MES) FROM CORRIDAS_MES;

--2ª Quais foram os top 10 dias que tivemos mais corridas?
SELECT 
    COUNT(*) AS TOTAL_CORRIDAS_DIA,
    DATE(STARTED_AT) AS DIA
FROM AT_SINCRONA_BD_POS_UNIFAP_01
GROUP BY DATE(STARTED_AT)
ORDER BY TOTAL_CORRIDAS_DIA DESC
LIMIT 10

--3ª Quais foram os top 10 dias que tiveram menos corridas?
SELECT 
    COUNT(*) AS TOTAL_CORRIDAS_DIA,
    DATE(STARTED_AT) AS dia
FROM AT_SINCRONA_BD_POS_UNIFAP_01
GROUP BY DATE(STARTED_AT)
ORDER BY TOTAL_CORRIDAS_DIA ASC
LIMIT 10

--4ª Quais são os top 5 pontos de início? Quantas corridas cada um teve?
SELECT 
    START_STATION_NAME AS NOME_PONTO_INICIO, 
    COUNT(*) AS TOTAL_CORRIDAS
FROM AT_SINCRONA_BD_POS_UNIFAP_01
WHERE START_STATION_NAME <> ''
GROUP BY NOME_PONTO_INICIO
ORDER BY TOTAL_CORRIDAS DESC
LIMIT 5;

--5ª Quais são os top 5 pontos de destino? Quantas corridas cada um teve?
SELECT 
    END_STATION_NAME AS NOME_PONTO_DESTINO, 
    COUNT(*) AS TOTAL_CORRIDAS
FROM AT_SINCRONA_BD_POS_UNIFAP_01
WHERE END_STATION_NAME <> ''
GROUP BY NOME_PONTO_DESTINO
ORDER BY TOTAL_CORRIDAS DESC
LIMIT 5;

--7ª Qual o tempo médio, por mês, de todas as corridas entre “Membros” e “Casuais”?
SELECT 
    STRFTIME('%Y-%m', STARTED_AT) AS MES,
    member_casual AS MEMBRO_OU_CASUAL,
    AVG(CAST((JULIANDAY(ENDED_AT) - JULIANDAY(STARTED_AT)) * 24 * 60 AS INTEGER)) AS TEMPO_MEDIO_EM_MINUTOS
FROM AT_SINCRONA_BD_POS_UNIFAP_01
GROUP BY MES, MEMBRO_OU_CASUAL
ORDER BY MES, MEMBRO_OU_CASUAL;

